### ISSUE TITLE
Prompt after rake:clean

### ISSUE THREAD

**Issue by darinwilson** [HipByte/motion-gradle#3]
After running `rake:clean` and rebuilding the project, I always see this prompt:

```
Create vendor/Gradle/build/libs/dependencies.jar.bridgesupport
replace /var/folders/hs/4337r5396qgb6lfqr9v65zj00000gn/T/__android_bridgesupport__/dependencies.jar/META-INF/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

Is it possible to skip that prompt? It might be nicer if the build could proceed without a prompt as it normally does, and this message could be a little confusing for new users.

**Comment by jjaffeux** [comment]
I do agree with you, however it happens in the unzip part of `gen_bridge_metadata` and right now I have no idea how to fix this.

Will need to investigate.

**Comment by darinwilson** [comment]
OK - it's only a minor annoyance right now, so it's probably not worth a deep dive. Thanks!

**Comment by jjaffeux** [comment]
@darinwilson OK I think I fixed it, can you try please when you have time (1.0.3) ?

**Comment by darinwilson** [comment]
I just tried it with 1.0.3 - I'm still getting the same behavior :(

**Comment by jjaffeux** [comment]
@darinwilson you might need to do a full rake clean:all and rake gradle:install before it works

**Comment by darinwilson** [comment]
Even with `rake clean:all` I still get the same behavior. 

```
[~/work]$ gem list --local

*** LOCAL GEMS ***

bigdecimal (1.2.3)
bundler (1.7.12)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
motion-gradle (1.0.3)
newclear (0.5)
PackingPeanut (0.0.3)
psych (2.0.2)
rake (10.4.2, 10.1.0)
rdoc (4.1.0)
reset-sim (1.0)
test-unit (2.1.0.0)
[~/work]$ rake clean:all
    Delete ./build
    Delete vendor/Gradle/build/libs/dependencies.jar.bridgesupport
    Delete /Users/darin/Library/RubyMotion/build
    Delete vendor/Gradle
[~/work]$ rake gradle:install
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:generateDependencies

BUILD SUCCESSFUL

Total time: 5.095 secs
[~/work]$ rake device
    Create ./build/Development-15/AndroidManifest.xml
warning: java/lang/Object.class(java/lang:Object.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
1 warning
    Create vendor/Gradle/build/libs/dependencies.jar.bridgesupport
replace /var/folders/hs/4337r5396qgb6lfqr9v65zj00000gn/T/__android_bridgesupport__/dependencies.jar/META-INF/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

Subsequent runs of `rake:clean; rake device` continue to put up the prompt. Is there another sequence of steps I should try?

**Comment by jjaffeux** [comment]
@darinwilson Ok I will investigate it this week-end, I'm pretty sure I have the right solution, but might be not at the right place.

**Comment by jjaffeux** [comment]
@darinwilson can you try 1.0.4 please ? pretty sure it will fix your issue.

**Comment by darinwilson** [comment]
@jjaffeux Oy...still happening. I did:

``` shell
rake clean:all
rake gradle:install
rake device
```

And the prompt appears. Is that what you're doing as well, or something different?

**Comment by jjaffeux** [comment]
@darinwilson can you paste the message? Is it still : 

```
replace /var/folders/hs/4337r5396qgb6lfqr9v65zj00000gn/T/__android_bridgesupport__/dependencies.jar/META-INF/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

or something else than `META-INF/LICENSE` ?

**Comment by darinwilson** [comment]
@jjaffeux Actually, it's `META-INF/NOTICE` now that I look at it more closely:

``` shell
replace /var/folders/hs/4337r5396qgb6lfqr9v65zj00000gn/T/__android_bridgesupport__/dependencies│
.jar/META-INF/NOTICE? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

**Comment by jjaffeux** [comment]
@darinwilson ok 1.0.5 should work :) if it still doesn't you know what I need to debug. But next time I will be more aggressive in what I exclude!

**Comment by darinwilson** [comment]
That's it! That finally did it. Thanks for perservering - much appreciated! :)
